### PR TITLE
Issue #302: add MissingJavadocMethod to CHECK_TO_ANCESTOR_NODES_MAP

### PR DESCRIPTION
**Pull request by HuGanghui**
Issue #302: add MissingJavadocMethod to CHECK_TO_ANCESTOR_NODES_MAP

### CODE REVIEW

**Comment by baratali** [comment]
https://github.com/checkstyle/patch-filters/issues/302#issuecomment-683308729

**Comment by HuGanghui** [comment]
rebased.

**Comment by HuGanghui** [comment]
according to discussion in https://github.com/checkstyle/patch-filters/issues/302#issuecomment-683781979, this PR will wait until https://github.com/checkstyle/checkstyle/issues/8778 is solved.

**Comment by baratali** [comment]
@HuGanghui , I said you could skip this check in https://github.com/checkstyle/patch-filters/issues/302#issuecomment-683781979. This fix is not correct anyway. I'm closing this PR.

**Pull request closed without merging**
