### PR TITLE
Issue #37: Take exact changed lines and only show violation on them, not all lines in patch file

### PR DESCRIPTION
**Pull request by HuGanghui**
Issue #37: Take exact changed lines and only show violation on them, not all lines in patch file

this need to clone https://github.com/HuGanghui/java-diff-utils/tree/addPosition and checkout to `addPosition` branch,  and then local install it. 

this is the first version, I think we need more tests to make sure it works.

### CODE REVIEW

**Comment by rdiachenko** [comment]
@HuGanghui please close this PR if no longer needed.

**Comment by HuGanghui** [comment]
@rdiachenko I think we still need to these changes in this PR, although we have a PR https://github.com/checkstyle/patch-filters/pull/65 that update current generators to a context size equal to 0, but the generators are suitable for projects that using git, not for using other CVS tools such as HG, and users may provide patch files with context size not equal to 0,  so I think it is necessary to take exact changed lines in patch-filter too, which is more general and guaranteed. Also PR is dependent on these changes.

**Comment by rdiachenko** [comment]
@HuGanghui please generate a report and provide evidence that your changes work fine.

**Comment by HuGanghui** [comment]
@rdiachenko diff report link is here: https://github.com/checkstyle/patch-filters/issues/37#issuecomment-655930031

**Comment by HuGanghui** [comment]
And I add UT to prove it works fine, please review.

**Comment by baratali** [comment]
@HuGanghui , please revert commit with "git revert" command and keep a generated commit title. Naming it just 'revert' is not good.

**Comment by HuGanghui** [comment]
@baratali done

**Comment by rdiachenko** [comment]
We are going to move to JGit as java-diff-utils has a lot of restrictions and doesn't suit our needs. This PR is closed in favor of https://github.com/checkstyle/patch-filters/issues/76

**Pull request closed without merging**
