### PR TITLE
Added default locale to avoid tests failed on non-English machine.

### PR DESCRIPTION
**Pull request by asakaxgit**
Roughly fixed issue #367.
Any side effects are out of consideration, but it works.

https://github.com/checkstyle/patch-filters/issues/367

### CODE REVIEW

**Comment by romani** [comment]
Thanks a lot , please fix CI failures

**Comment by rnveach** [comment]
@romani CI failures are because this repo is abandoned. Not related to this PR.

**Comment by romani** [comment]
Link should be https://raw.githubusercontent.com/checkstyle/checkstyle/master/config/java-regexp.header

At https://github.com/checkstyle/patch-filters/blob/3fabf1afda38fa3ec05c9dbbd5b540e3be07526e/config/checkstyle.properties#L4

@asakaxgit , please do this update in same PR.

**Comment by asakaxgit** [comment]
> Link should be https://raw.githubusercontent.com/checkstyle/checkstyle/master/config/java-regexp.header
> 
> At
> 
> https://github.com/checkstyle/patch-filters/blob/3fabf1afda38fa3ec05c9dbbd5b540e3be07526e/config/checkstyle.properties#L4
> 
> @asakaxgit , please do this update in same PR.

Fixed.
https://github.com/checkstyle/patch-filters/pull/368/commits/d52dfdcde23a35283d46258549b141cd750eae2c
https://github.com/checkstyle/patch-filters/pull/368/commits/52d2291575ee2d2d9766254dbb5766eb7f1d47a4

**Pull request merged**
